/**
 * @file    sx1262.h
 * @brief   Mid-level driver for the SX1262 sub-GHz radio chip.
 *
 *   The Semtech sx126x_driver is a thin, chip-level library. It knows how
 *   to encode every command the chip understands, but it has no opinion on
 *   how those commands should be sequenced, when to switch between TX and RX,
 *   or how to manage external RF frontend circuitry (e.g. an RF switch).
 *
 *   This module fills that gap. It owns:
 *     - The initialization sequence required by this board's hardware (DC-DC,
 *       calibration, TxClamp workaround).
 *     - The LoRa radio configuration (frequency, SF, BW, CR, PA power).
 *     - The TX/RX state machine, driven by DIO1 interrupts.
 *     - The RF switch control, delegated to the BSP via callbacks.
 *
 *   Crucially, this module contains NO board-specific pin references.
 *   All hardware access is performed through the sx1262_config_t that the
 *   BSP constructs and injects via sx1262_init(). This makes the driver
 *   portable: any board with a SX1262 can reuse it by providing its own
 *   sx1262_config_t without touching this file.
 *
 *   Dependency rule:
 *   This file MUST NOT include any STM32 HAL headers, gpio.h, spi.h, or
 *   any BSP header. The only allowed external includes are:
 *     - sx126x.h           (Semtech driver public API)
 *     - Standard C headers (stdint.h, stdbool.h, stddef.h)
 */

#ifndef DRIVERS_SX1262_SX1262_H_
#define DRIVERS_SX1262_SX1262_H_

#include "sx126x.h"
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * sx1262_config_t is the single point of injection between the BSP and this
 * driver. The BSP constructs one instance with all the board-specific details
 * and passes it to sx1262_init(). After that, this driver never calls back
 * into the BSP.
 *
 * Why callbacks for the RF switch and not direct GPIO calls?
 * Because the RF switch (PE4259 on this board) is external circuitry that
 * varies between board revisions and designs. Encoding its control here would
 * couple this driver to a specific PCB layout. The callback approach lets the
 * BSP own that knowledge and keeps this driver board-agnostic.
 */

/**
 * @brief Callback type for RF switch control.
 *
 * The BSP must provide two functions matching this signature:
 *   - one that routes the RF path to TX
 *   - one that routes the RF path to RX
 */
typedef void (*sx1262_rf_switch_fn_t)(void);

/**
 * @brief Complete configuration for the SX1262 driver.
 *
 * Constructed by the BSP and passed once to sx1262_init().
 * Must remain valid for the entire lifetime of the driver.
 */
typedef struct {
  /**
   * Hardware context for the Semtech sx126x HAL.
   * Carries SPI handle and GPIO descriptors for NSS, RESET, BUSY, DIO1.
   * This is what the Semtech driver needs to perform SPI transactions.
   */
  const void *hal;

  /**
   * RF switch callbacks — board-specific, implemented in the BSP.
   * Called by sx1262_set_tx() and sx1262_set_rx() respectively.
   * May be NULL only if the board has no external RF switch.
   */
  sx1262_rf_switch_fn_t set_tx;
  sx1262_rf_switch_fn_t set_rx;

  /**
   * @brief Hook for registering the chip's IRQ handler with the platform.
   *
   * Provided by the BSP. When the driver invokes this during sx1262_init(),
   * the BSP internally connects the correct EXTI pin to
   * sx1262_dio1_irq_handler().
   *
   * The driver never knows which pin triggers the IRQ — that is the exclusive
   * responsibility of the BSP.
   *
   * May be NULL if the platform does not use interrupts (polling mode).
   */
  void (*register_irq_handler)(void (*handler)(void));

  struct {
    uint32_t frequency_hz;
    sx126x_lora_sf_t sf;
    sx126x_lora_bw_t bw;
    sx126x_lora_cr_t cr;
    int8_t tx_power_dbm;
    uint8_t sync_word;
    bool use_dcdc;
  } radio;
} sx1262_config_t;

/**
 * @brief Snapshot of the SX1262 internal state, as reported by GetStatus.
 *
 * chip_mode values (table 13-76 of the datasheet):
 *   0x02 = STDBY_RC, 0x03 = STDBY_XOSC, 0x04 = FS,
 *   0x05 = RX,       0x06 = TX
 *
 * cmd_status values:
 *   0x01 = command processed OK (no data returned)
 *   0x02 = data available for host
 *   0x03 = command timeout
 *   0x04 = command processing error
 *   0x05 = failure to execute
 *   0x06 = TX done
 */
typedef struct {
  uint8_t chip_mode;
  uint8_t cmd_status;
} sx1262_chip_status_t;

/**
 * @brief Events generated by the DIO1 ISR and consumed by the application.
 *
 * Only one event can be pending at a time. If a new IRQ fires before the
 * application reads the previous event, the new event overwrites the old one.
 * This is acceptable for a single-channel driver; a queue-based approach
 * should be considered when RTOS is introduced.
 */
typedef enum {
  SX1262_EVENT_NONE = 0,  /**< No pending event.                     */
  SX1262_EVENT_TX_DONE,   /**< Packet transmitted successfully.      */
  SX1262_EVENT_RX_DONE,   /**< Packet received and ready to read.    */
  SX1262_EVENT_CRC_ERROR, /**< Received packet failed CRC check.     */
  SX1262_EVENT_TIMEOUT,   /**< RX or TX operation timed out.         */
} sx1262_irq_event_t;

/** Maximum payload length supported by the LoRa packet format. */
#define SX1262_PAYLOAD_MAX_LEN 255U

/**
 * @brief Initialise the driver with a board-supplied configuration.
 *
 * Must be called before any other sx1262_* function. Does NOT touch the
 * hardware — hardware initialisation is performed by sx1262_chip_config().
 *
 * @param config  Pointer to a BSP-owned configuration struct. Must not be
 *                NULL and must remain valid for the lifetime of the driver.
 * @return true   if the configuration is valid and the driver is ready.
 * @return false  if config or any mandatory field within it is NULL.
 */
bool sx1262_init(const sx1262_config_t *config);

/**
 * @brief Perform the hardware initialisation sequence.
 *
 * Must be called after sx1262_init().
 */
void sx1262_chip_config(void);

/**
 * @brief Configure the radio for LoRa operation.
 *
 * Must be called after sx1262_chip_config().
 */
void sx1262_radio_config(void);

/**
 * @brief Read the current chip status.
 *
 * @param[out] out  Populated with chip_mode and cmd_status on success.
 * @return true     if the chip responded and chip_mode is non-zero.
 * @return false    if the SPI transaction failed or the chip is unresponsive.
 */
bool sx1262_chip_status(sx1262_chip_status_t *out);

/**
 * @brief Prepare the chip for transmission.
 *
 * Routes the RF switch to the TX path and configures DIO1 to fire on
 * TX_DONE or TIMEOUT. Call this once before the first sx1262_send_payload()
 * call. There is no need to call it again between consecutive packets.
 */
void sx1262_set_tx(void);

/**
 * @brief Write a payload to the chip buffer and start transmission.
 *
 * Non-blocking: returns immediately after issuing SetTx to the chip.
 * The application must wait for SX1262_EVENT_TX_DONE via sx1262_get_event().
 *
 * Precondition: sx1262_set_tx() must have been called beforehand.
 *
 * @param payload  Data to transmit. Must not be NULL.
 * @param length   Number of bytes. Must be > 0 and <= SX1262_PAYLOAD_MAX_LEN.
 * @return true    if the payload was written and SetTx was issued.
 * @return false   if payload is NULL or length is out of range.
 */
bool sx1262_send_payload(const uint8_t *payload, uint8_t length);

/**
 * @brief Put the chip into continuous receive mode.
 *
 * Routes the RF switch to the RX path, configures DIO1 to fire on
 * RX_DONE, CRC_ERROR, or TIMEOUT, then issues SetRx with no timeout
 * (the chip listens indefinitely).
 *
 * Must be called again after each received packet (i.e. after processing
 * SX1262_EVENT_RX_DONE) because the chip returns to STDBY after reception.
 */
void sx1262_set_rx(void);

/**
 * @brief Read the last received packet from the chip's internal buffer.
 *
 * Call this only after sx1262_get_event() returns SX1262_EVENT_RX_DONE.
 * The data has been sitting in the chip's buffer since the packet arrived.
 *
 * @param[out] out_buf     Destination buffer. Must be at least
 *                         SX1262_PAYLOAD_MAX_LEN bytes.
 * @param[out] out_length  Set to the actual number of bytes received.
 * @return true            if the buffer status was read and data was copied.
 * @return false           if the SPI transaction failed.
 */
bool sx1262_read_received_packet(uint8_t *out_buf, uint8_t *out_length);

/**
 * These two functions form the contract between the BSP interrupt layer
 * and the application event loop.
 *
 * The split is intentional:
 *   sx1262_dio1_irq_handler() runs in interrupt context — it must be as
 *   short as possible (no SPI, no blocking calls, no printf).
 *
 *   sx1262_get_event() runs in task/main-loop context — it is the only
 *   place where the pending event is consumed and the IRQ status is read.
 **/

/**
 * @brief ISR handler — call from the EXTI callback for DIO1.
 *
 * Sets an internal flag indicating that a DIO1 edge was detected.
 * The actual IRQ status register is read lazily in sx1262_get_event()
 * to keep interrupt latency minimal and avoid SPI inside ISR context.
 *
 * Registration is performed automatically during sx1262_init() via the
 * register_irq_handler callback in sx1262_config_t. The BSP connects
 * this function to the correct EXTI pin internally; no manual wiring
 * is needed at the application layer.
 */
void sx1262_dio1_irq_handler(void);

/**
 * @brief Consume and return the pending IRQ event.
 *
 * Reads the chip's IRQ status register over SPI (deferred from the ISR),
 * clears the IRQ flags in the chip, translates them to sx1262_irq_event_t,
 * and resets the internal pending flag.
 *
 * Returns SX1262_EVENT_NONE if no event is pending.
 *
 * Thread safety: safe to call from a single task or from the main loop.
 * If RTOS is introduced, protect the pending-flag read with a
 * binary semaphore rather than __disable_irq().
 */
sx1262_irq_event_t sx1262_get_event(void);

/** Diagnostic counter — number of DIO1 edges observed since reset. */
extern volatile uint32_t sx1262_isr_count;

#ifdef __cplusplus
}
#endif

#endif /* DRIVERS_SX1262_SX1262_H_ */